// CheCklists do faturamento
export const CHECKLISTS = {
    compras: [
        "Inserir 1 solicitação de compra de matéria-prima",
        "Inserir 1 solicitação de compra de serviços",
        "Inserir 1 solicitação de compra de materiais de consumo",
        "Inserir 1 solicitação de compra de materiais de estoque",
        "Inserir 1 solicitação de compra de ativo fixo",
        "Efetuar aprovação das solicitações de compra",
        "Pedidos de Compra",
        "Inserir Pedido de compra de matéria-prima",
        "Inserir pedido de compra de serviços",
        "Inserir pedido de compra de materiais de consumo",
        "Inserir pedido de compra de materiais de estoque",
        "Inserir pedido de compra de ativo fixo",
        "Efetuar liberação de pedidos",
        "Registro de Notas Fiscais de Entrada",
        "Inserir nota fiscal de compra de matéria-prima",
        "Inserir nota fiscal de compra de serviços",
        "Inserir nota fiscal de compra de materiais de consumo",
        "Inserir nota fiscal de compra de materiais de estoque",
        "Inserir nota fiscal de devoluções",
        "Inserir nota fiscal de transferência ativo fixo e produtos",
        "Inserir nota fiscal de complemento - Impostos e preços",
        "Inserir nota fiscal de conhecimento de frete",
        "Inserir nota fiscal de despesa de importação",
        "Inserir nota fiscal de compra de ativo fixo",
        "Relatórios",
        "Imprimir relatório de solicitações de compras",
        "Imprimir Relação das Notas Fiscais",
        "Imprime solicitação de compras ",
        "Relatório de Histórico de Pedido de Compras",
        "Relatório de Pedido de Compras Personalizado",
        "Relatório Base QVP",
        "Contabilização",
        "Integralização contábil da Notas entradas",
        "Integralização contábil de Conhecimento de Frete",
    ],

    faturamento: [
        "Inserir orçamento de Venda Normal",
        "Efetivação do orçamento de venda",
        "Inserir pedido de venda para venda normal",
        "inserir pedido de venda para venda (iPad)",
        "inserir pedido de venda para venda c/ antecipação",
        "inserir pedido de venda para demonstração",
        "inserir pedido de complemento de preço - impostos",
        "Inserir Pedido de Venda de Complemento de Preço",
        "Inserir Pedido de Venda de Complemento de IPI",
        "Inserir Pedido de Venda de Complemento de ICMS",
        "inserir pedido de venda para exportação",
        "inserir pedido de venda para transferência",
        "inserir pedido de venda para venda de ativo",
        "inserir pedido de venda de remessa para conserto",
        "inserir pedido de venda de remessa para empréstimo",
        "inserir pedido de venda para devolução a fornecedor",
        "inserir pedido de venda para comodato",
        "Inserir pedido de venda de material não produtivo",
        "Inserir pedido de venda de Triangular",
        "Inserir pedido de venda de Venda entrega Futura",
        "Liberação de Pedido de Venda",
        "Liberação e Analise de Credito",
        "Liberação Estoque Total e Parcial",
        "Gerar documentos de saída para os pedidos de venda teste inseridos",
        "Imprimir documentos de saída de venda entrega futura",
        "Imprimir documentos de saída de demonstração",
        "Imprimir documentos de saída de transferência",
        "Imprimir documentos de saída de venda de ativo",
        "Imprimir documentos de saída de remessa para conserto",
        "Imprimir documentos de saída de remessa para empréstimo",
        "Imprimir documentos de saída de devolução ao fornecedor",
        "Imprimir documentos de saída complemento de preço - impostos",
        "Imprimir documentos de saída de comodato",
        "Imprimir romaneio de separação",
        "Relação de Orçamento",
        "Pedido de Vendas por Produto",
        "Imprimir relatório de notas fiscais",
        "Pedido de Vendas X Clientes",
        "Pedido de Vendas X Produtos",
        "Pedido de Vendas por Produto",
        "Pedido de Vendas não Entregues",
        "Pedidos a Faturar",
        "Pick List a Faturar",
        "Pick List de Pedidos",
        "Faturamento por Prazo",
        "Faturamento por Vendedor",
        "Faturamento por Cliente",
        "Faturamento Cliente X Produto",
        "Resumo de Vendas",
        "Impressão da nota fiscal (E/S) (produtos/serviços)",
    ],

    contabilidade: [
        "Cadastro de calendário contábil",
        "Cadastro de moedas contábeis",
        "Cadastro de cambio",
        "Cadastro de amarração moedas x calendário contábil",
        "Cadastro de Lançamento Padrão",
        "Cadastro de configurações contábeis",
        "Cadastro de Plano de Contas",
        "Cadastro de centros de custos",
        "Cadastro de Item Contábil",
        "Cadastro de amarrações",
        "Cadastro de visões gerenciais (DRE, Balanço Patrimonial)",
        "Cadastro de histórico inteligente",
        "Cadastro de relacionamentos",
        "Cadastro de câmbio de moedas",
        "Lançamentos Contábeis",
        "Lançamentos Contábeis Automáticos",
        "Fechamento Mensal/Anual",
        "Conciliação Contábil",
        "Apuração de lucros e perdas (mensal/anual).",
        "Encerramento de exercício",
        "Cadastro de Participante",
        "Cadastro do Contabilista",
        "Plano Referencial x Plano de Contas",
        "Reprocessamento",
        "Efetivação de Pré-Lançamento",
        "Tratamento das Entidades Contábeis (Segmentos)",
        "Pré-Requisitos da Gestão Contábil",
        "Escrituração Contábil",
        "Geração do Arquivo",
        "Sped Contábil",
        "Geração do Arquivo Sped",
        "Relatórios",
        "Conferencia de digitação",
        "Balancete modelo 1",
        "Balancete por Centro de Custo",
        "Balancete por item contábil",
        "Balancete por conta X centro de custo",
        "Balancete Item x conta",
        "Balancete clvl x conta",
        "Razão contábil",
        "Razão por centro de custo",
        "Diário contábil",
        "Validar Relatórios com Visão Gerencial",
        "Razão analítico",
        "Levantamento de custos RELATORIO",
        "Relação dos custos por CC e conta",
        "Contabilização",
        "Importação dos lançamentos contábeis arquivo",
    ],

    livros_fiscais: [
        "Cadastro de calendário contábil",
        "Cadastro de moedas contábeis",
        "Cadastro de cambio",
        "Cadastro de amarração moedas x calendário contábil",
        "Cadastro de Lançamento Padrão",
        "Cadastro de configurações contábeis",
        "Cadastro de Plano de Contas",
        "Cadastro de centros de custos",
        "Cadastro de Item Contábil",
        "Cadastro de amarrações",
        "Cadastro de visões gerenciais (DRE, Balanço Patrimonial)",
        "Cadastro de histórico inteligente",
        "Cadastro de relacionamentos",
        "Cadastro de câmbio de moedas",
        "Lançamentos Contábeis",
        "Lançamentos Contábeis Automáticos",
        "Fechamento Mensal/Anual",
        "Conciliação Contábil",
        "Apuração de lucros e perdas (mensal/anual).",
        "Encerramento de exercício",
        "Cadastro de Participante",
        "Cadastro do Contabilista",
        "Plano Referencial x Plano de Contas",
        "Reprocessamento",
        "Efetivação de Pré-Lançamento",
        "Tratamento das Entidades Contábeis (Segmentos) ",
        "Pré-Requisitos da Gestão Contábil",
        "Escrituração Contábil",
        "Geração do Arquivo",
        "Sped Contábil",
        "Geração do Arquivo Sped",
        "Relatórios",
        "Conferencia de digitação",
        "Balancete modelo 1",
        "Balancete por Centro de Custo",
        "Balancete por item contábil",
        "Balancete por conta X centro de custo",
        "Balancete Item x conta",
        "Balancete clvl x conta",
        "Razão contábil",
        "Razão por centro de custo",
        "Diário contábil",
        "Validar Relatórios com Visão Gerencial",
        "Razão analítico",
        "Levantamento de custos RELATORIO",
        "Relação dos custos por CC e conta",
        "Contabilização",
        "Importação dos lançamentos contábeis arquivo",
    ],

    contas_pagar: [
        "Simular a inserção de títulos a pagar  (Normal, Abatimento, PA, NDF)",
        "Simular contabilização",
        "Efetuar baixas a pagar manual e automática",
        "Efetuar compensação de conta a pagar",
        "Gerar CNAB a pagar",
        "Gerar ",
        "Impressão de cheques",
        "Efetuar movimentação e lançamento no Caixinha",
        "Efetuar movimentação e baixa de caixinha",
        "Efetuar geração de 1 borderô ",
        "Movimentos - Bancária",
        "Movimentação Bancária",
        "Conciliação Bancária",
        "Relatórios",
        "Imprimir relatório Eficiência de Contas a pagar",
        "Emitir relatório Extrato Bancário",
        "Emitir relatório Movimento Financeiro diário",
        "Emitir relatório Relação de Baixas",
        "Relatório de movimentação do caixinha",
        "Posição dos Títulos a Pagar",
        "Posição dos Clientes",
        "Borderô de Pagamento",
        "Funcionalidades adicionais",
        "Estorno de 1 adiantamento",
        "Contabilização",
        "Integralização das baixas de borderô e dos cheques",
    ],

    contas_receber: [
        "Simular a inserção de títulos a receber  ( Normal, Abatimento, RA ,NCC)",
        "Simular contabilização",
        "Efetuar 1 baixa a receber  manual e automatica",
        "Efetuar 1 compensação de conta a receber",
        "Efetuar geração de 1 borderô ",
        "Simular todos os processos de negociação",
        "Efetuar consulta na Ficha Financeira (Vários Casos) e todas as opções.",
        "Transferência entre Carteiras",
        "Movimentos - Bancária",
        "Movimentação Bancária",
        "Conciliação Bancária",
        "Relatórios",
        "Imprimir relatório Eficiência de Contas a pagar",
        "Emitir relatorio Extrato Bancário",
        "Emitir relatório Movimento Financeiro diário",
        "Emitir relatório Relação de Baixas",
        "Relatorio de movimentacao do caixinha",
        "Posicao dos Titulos a Pagar",
        "Posicao dos Clientes",
        "Bordero de Pagamento",
        "Funcionalidades adicionais",
        "Estorno de 1 adiantamento",
        "Contabilização",
        "Integralização das baixas de bordero e dos cheques",
    ],

    estoque: [
        "Efetuar transferência interna de estoque (somente p/ teste)",
        "Abrir Ordem de Produção",
        "Ajuste de Empenho",
        "Apontamento de Perdas",
        "Apontamento de Produção",
        "Saldos Iniciais",
        "Simular Solicitação Almoxarifado",
        "Apuração de Custos",
        "Fechamento de Estoque",
        "Efetuar requisição de material",
        "Relatórios",
        "Imprimir relatório Saldo de Estoque",
        "Imprimir relatório Posição de Estoque",
        "Imprimir relatório Entradas e Saídas",
        "Imprimir relatório Kardex por dia",
        "Lista produtos, quantidade e local (armazém)",
        "Processamento",
        "Simular fechamento de estoque",
        "Efetuar analise do custo médio (Produtos em Geral / Grãos)",
        "Funcionalidades adicionais",
        "Requisição de materiais para estoque (Solicitação Almoxarifado)",
        "Contabilização",
        "Integralização das baixas e movimentações",
        "Integralização da contabilização do Custo Médio (PA/MP)",
        "Integralização da contabilização do Custo Médio (Produto em Geral)",
    ],

    pcp_mggold: [
        "Efetuar transferência interna de estoque (somente p/ teste)",
        "Incluir saldos Iniciais",
        "Incluir Estrutura de Produto",
        "Abrir Ordem de produção",
        "Ajuste de Empenho",
        "Apontamento de Perdas",
        "Apontamento de Produção",
        "Apuração de Custos",
        "Fechamento de Estoque",
        "Efetuar requisição de material",
        "Relatórios",
        "Imprimir relatório Saldo de Estoque",
        "Imprimir relatório Posição de Estoque",
        "Imprimir relatório Entradas e Saídas",
        "Imprimir ordem de produção",
        "Imprimir movimentos internos (MATR300)",
        "Imprimir relação das OP (MATR850)",
        "Imprimir relação por OP (MATR860)",
        "Imprimir relatório Kardex por dia",
        "Lista produtos, quantidade e local (armazém)",
        "Processamento",
        "Simular fechamento de estoque",
        "Efetuar analise do custo médio (produção)",
        "Funcionalidades adicionais",
        "Requisição de materiais para estoque (Solicitação Almoxarifado)",
        "Contabilização",
        "Integralização das baixas e movimentações",
        "Integralização da contabilização do Custo Médio (Produção)",
    ],

    pcp_magnum: [
        "Efetuar transferência interna de estoque (somente p/ teste)",
        "Incluir saldos Iniciais",
        "Incluir Estrutura de Produto",
        "Abrir Ordem de produção",
        "Ajuste de Empenho",
        "Apontamento de Perdas",
        "Apontamento de Produção",
        "Apuração de Custos",
        "Fechamento de Estoque",
        "Efetuar requisição de material",
        "Relatórios",
        "Imprimir relatório Saldo de Estoque",
        "Imprimir relatório Posição de Estoque",
        "Imprimir relatório Entradas e Saídas",
        "Imprimir ordem de produção",
        "Imprimir movimentos internos (MATR300)",
        "Imprimir relação das OP (MATR850)",
        "Imprimir relação por OP (MATR860)",
        "Imprimir relatório Kardex por dia",
        "Lista produtos, quantidade e local (armazém)",
        "Processamento",
        "Simular fechamento de estoque",
        "Efetuar analise do custo médio (produção)",
        "Funcionalidades adicionais",
        "Requisição de materiais para estoque (Solicitação Almoxarifado)",
        "Contabilização",
        "Integralização das baixas e movimentações",
        "Integralização da contabilização do Custo Médio (Produção)",
    ],
}