export const DEPARTAMENTOS = [
    "COMPRAS",
    "FATURAMENTO",
    "CONTABILIDADE",
    "LIVROS FISCAIS",
    "FINANCEIRO - CP",
    "FINANCEIRO - CR",
    "ESTOQUE",
    "PCP - MGGOLD",
    "PCP - MAGNUM"
];